### ISSUE TITLE
iCub_SIM feature parity

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#132]
This is a meta-issue to track all the things necessary for the iCub simulation based on gazebo-yarp-plugins to be a drop-in replacement for iCub_SIM [1] :
- [x] Windows support, see issue https://github.com/robotology/gazebo-yarp-plugins/issues/74 
- [x] Eyes/vision support, see issue https://github.com/robotology/gazebo-yarp-plugins/issues/149
  - [x] Full camera support, see issue https://github.com/robotology/gazebo-yarp-plugins/issues/96
  - [x] iCub eyes URDF/SDF model
  - [x] Support for mixed position/velocity control of simply coupled mechanisms in `gazebo_yarp_controlboard`
- [x] Hands/Manipulation support, , see issue https://github.com/robotology/gazebo-yarp-plugins/issues/197
  - [x] iCub hands URDF/SDF model 
  - [x] Support for position control of under-actuated mechanisms in `gazebo_yarp_controlboard`
- [x] `/world` port, see issue #159
  - [x] basic shape creation using yarp /world port 
  - [ ] spawning complex objects using yarp /world port
  - [x] "hand of god" plugin for fixing an object to a robot hand
- [x] Support for projecting a video in a model texture
- [x] Support for face expressions (https://github.com/robotology/cer-sim/issues/17)
- [ ] Support for basic skin simulation, see issue https://github.com/robotology/gazebo-yarp-plugins/issues/55
- [x] Support for all icub control modes

Some features perhaps are not strictly necessary, this should be asked to the iCub_SIM users. For some of them we can switch to facilities that Gazebo already offers (for example the complex object creation thought the /world port can be substituted by normal model spawning in Gazebo using the `gz model` command).

cc @lornat75 

[1] : Documentation of the iCub_SIM features: http://eris.liralab.it/wiki/Simulator_README .

**Comment by traversaro** [comment]
Regarding the use of the world port for spawning complex object, we should check with @tanismar because it is the worldwide expert user of that feature in `iCub_SIM`.

**Comment by lornat75** [comment]
I wonder if face expressions are really needed :)

**Comment by traversaro** [comment]
:D

**Comment by lornat75** [comment]
About windows intallation: @aerydna has started compiling gazebo on Windows. I don't know if he was successful (cc @randaz81).

**Comment by traversaro** [comment]
@aerydna There are some PR to watch out that improved Gazebo support for Windows : 
* https://bitbucket.org/osrf/gazebo/pull-requests/2311/ensure-plugin-and-plugin-macros-are-always/diff <-- This should enable loading of plugin on Windows
* https://bitbucket.org/osrf/gazebo/pull-requests/2175 <-- This PR was declined because it was quite messy and incorporated a lot of unnecessary changes , but it included several real fixes/improvement to compile Gazebo with Visual Studio rather then using NMake.

**Comment by traversaro** [comment]
Support for face expression can be implemented via the `videotexture` plugin, see https://github.com/robotology/cer-sim/issues/17 .

**Comment by aerydna** [comment]
@traversaro @fiorisi it require to do some work on the texture mapping of the icub meshes. very easy to do manually (i'll do it soon just to see it working) but maybe complicated to integrate it in the worflow of the icub mesh production?

**Comment by traversaro** [comment]
@traversaro I think we can open a separate issue for this in https://github.com/robotology/icub-model-generator . This issue is about the features required in gazebo-yarp-plugins. For iCub model specific we can open an  issue in the icub-model-generator repo.

**Comment by traversaro** [comment]
As  Windows support has been achieved (see https://github.com/robotology/gazebo-yarp-plugins/issues/74), the last two missing points are: 
* spawning complex objects using yarp /world port
* Support for basic skin simulation, see issue https://github.com/robotology/gazebo-yarp-plugins/issues/55

The functionality described in the first issue are probably superseeded by Gazebo built-in functionalities, while for what regards skin simulation I think it is more useful to just track if anyone is interested on working on this in  https://github.com/robotology/gazebo-yarp-plugins/issues/55 . 
Given this, I think it make sense to just close this issue.
